"""empty message

Revision ID: 2cfc5e1fc0da
Revises: fe2010fb4a7d
Create Date: 2017-02-16 12:24:21.471504

"""

# revision identifiers, used by Alembic.
revision = '2cfc5e1fc0da'
down_revision = 'fe2010fb4a7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('article', sa.String(length=2500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'article')
    # ### end Alembic commands ###
