"""empty message

Revision ID: c6af0c616d31
Revises: 2cfc5e1fc0da
Create Date: 2017-02-16 15:28:01.679826

"""

# revision identifiers, used by Alembic.
revision = 'c6af0c616d31'
down_revision = '2cfc5e1fc0da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tag', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'tag', ['tag'], ['id'])
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('image', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'tag', 'image', ['image'], ['id'])
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'tag')
    # ### end Alembic commands ###
